<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2014 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'acceptable_sugar_versions' => 
  array (
    'regex_matches' => array(
	  '7\\.[0-9]\\.[0-9]$'
	),
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'ENT',
    2 => 'ULT',
  ),
  'readme' => 'README.txt',
  'key' => 'RSSD',
  'author' => 'Masaki Fukumitsu',
  'description' => 'RSS/Atom Feed Dashlet',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Feed Dashlet',
  'published_date' => '2014-07-18 09:31:53',
  'type' => 'module',
  'version' => '1.0.0',
  'remove_tables' => false,
);


$installdefs = array (
  'id' => 'FEEDDASHLET',
  'relationships' => 
  array (
  ),
  'custom_fields' => 
  array (
    'Accountsfeed_url_c' => 
    array (
      'id' => 'Accountsfeed_url_c',
      'name' => 'feed_url_c',
      'label' => 'LBL_FEED_URL',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    array (
      'from' => '<basepath>/custom/clients/base/api/rssapi.php',
      'to' => 'custom/clients/base/api/rssapi.php',
    ),
    array (
      'from' => '<basepath>/custom/clients/base/views/feed/',
      'to' => 'custom/clients/base/views/feed/',
    ),
    array (
      'from' => '<basepath>/custom/vendor/simplepie/',
      'to' => 'custom/vendor/simplepie/',
    ),
  ),
  'language' => 
  array (
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/ja_JP.lang.php',
      'to_module' => 'application',
      'language' => 'ja_JP',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Accounts/Ext/Language/en_us.lang.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/custom/Extension/modules/Accounts/Ext/Language/ja_JP.lang.php',
      'to_module' => 'Accounts',
      'language' => 'ja_JP',
    ),
  ),
);